feat: add advertiser_tracking_enabled to server-event (#249)
Summary:
Fixes https://github.com/facebook/facebook-nodejs-business-sdk/issues/233. This PR adds the `setAdvertiserTrackingEnabled(advertiser_tracking_enabled: boolean)` method to the `ServerEvent` class.

I have not added any new tests, following the style of code/test in other methods of the `ServerEvent` class.  If you would like tests to be added, please let me know!

There is a pre-existing failing test in unchanged code:

```
 FAIL  __tests__/signal.test.js
  ● Signal Data › Event › Event creation

    ReferenceError: data_processing_options_state is not defined

      at ServerEvent.data_processing_options_state (dist/objects/serverside/server-event.js:381:41)
      at Event.setDataProcessingOptionsState (dist/objects/signal/event.js:348:9)
      at Object.setDataProcessingOptionsState (__tests__/signal.test.js:394:18)
```

I attempted to run the semistandard linter, but it ended up with changes to every single src file -- not sure if there is a config error in the repo somewhere?

Thanks! 😄

Pull Request resolved: https://github.com/facebook/facebook-nodejs-business-sdk/pull/249

Reviewed By: mengxuanzhangz

Differential Revision: D46075345

Pulled By: stcheng

fbshipit-source-id: c569682c1583d8cb8610d01b955487a6bd332374